{
 "title": "JVM Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "节点",
    "query": {
     "query": "label_values(jvm_used_mb,_node)"
    }
   },
   {
    "name": "namespace",
    "label": "用户空间",
    "query": {
     "query": "label_values(jvm_used_mb{_node=~\"^$node\"},_namespace)"
    }
   },
   {
    "name": "container",
    "label": "应用",
    "query": {
     "query": "label_values(jvm_used_mb{_node=~\"^$node\",_namespace=~\"^$namespace\"},_container)"
    }
   },
   {
    "name": "pod",
    "label": "pid",
    "query": {
     "query": "label_values(jvm_used_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\"},_pod)"
    }
   },
   {
    "name": "heapPoolName",
    "query": {
     "query": "label_values(jvm_heap_mp_used_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"}, poolName)"
    }
   },
   {
    "name": "nonheapPoolName",
    "query": {
     "query": "label_values(jvm_nonheap_mp_used_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"}, poolName)"
    }
   },
   {
    "name": "dsJndiName",
    "query": {
     "query": "label_values(jvm_ds_idle{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"}, jndi)"
    }
   },
   {
    "name": "disk",
    "label": "硬盘",
    "query": {
     "query": "label_values(node_disk_readMs{_node=~\"^$node\"},disk)"
    }
   }
  ]
 },
 "panels": [
  { "title": "节点CPU、总内存、硬盘监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_cpu_idle{_node=~\"^$node\"})/sum(node_cpu_total{_node=~\"^$node\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(node_cpu_user{_node=~\"^$node\"})/sum(node_cpu_total{_node=~\"^$node\"})",
     "legendFormat": "user"
    },
    {
     "expr": "sum(node_cpu_iowait{_node=~\"^$node\"})/sum(node_cpu_total{_node=~\"^$node\"})",
     "legendFormat": "iowait"
    }
   ]
  },
  {
   "title": "节点内存（单位：MB）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_mem_buff_cache{_node=~\"^$node\"})",
     "legendFormat": "缓冲缓存"
    },
    {
     "expr": "sum(node_mem_total{_node=~\"^$node\"}) - sum(node_mem_free{_node=~\"^$node\"}) - sum(node_mem_buff_cache{_node=~\"^$node\"})",
     "legendFormat": "已用内存"
    },
    {
     "expr": "sum(node_mem_free{_node=~\"^$node\"})",
     "legendFormat": "空闲内存"
    }
   ]
  },
  {
   "title": "硬盘IO（单位：KB/s）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(node_disk_writeHalfKB{_node=~\"^$node\",disk=~\"^$disk\"})*500)/sum(node_disk_writeMs{_node=~\"^$node\",disk=~\"^$disk\"})",
     "legendFormat": "硬盘写"
    },
    {
     "expr": "(sum(node_disk_readHalfKB{_node=~\"^$node\",disk=~\"^$disk\"})*500)/sum(node_disk_readMs{_node=~\"^$node\",disk=~\"^$disk\"})",
     "legendFormat": "硬盘读"
    }
   ]
  },
  { "title": "JVM内存监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "JVM总内存（单位：MB）",
   "type": "graph",
   "gridPos": { "h": 4, "w": 22, "x": 1, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_max_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "最大内存"
    },
    {
     "expr": "sum(jvm_committed_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "已分配内存"
    },
    {
     "expr": "sum(jvm_used_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "已用内存"
    }
   ]
  },
  {
   "title": "Heap堆内存（单位：MB）",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_heap_max_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "最大"
    },
    {
     "expr": "sum(jvm_heap_committed_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "已分配"
    },
    {
     "expr": "sum(jvm_heap_used_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "已用"
    }
   ]
  },
  {
   "title": "堆外内存（单位：MB）",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_nonheap_max_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "最大"
    },
    {
     "expr": "sum(jvm_nonheap_committed_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "已分配"
    },
    {
     "expr": "sum(jvm_nonheap_used_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "已用"
    }
   ]
  },
  {
   "title": "直接内存（单位：MB）",
   "type": "graph",
   "description": "Direct Memory",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_buffer_max{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "已分配"
    },
    {
     "expr": "sum(jvm_buffer_used{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "使用中"
    }
   ]
  },
  { "title": "GC监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Full GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_gc_full_time_ms{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "GC耗时(毫秒)"
    },
    {
     "expr": "sum(jvm_gc_full_count{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "GC次数"
    },
    {
     "expr": "sum(jvm_gc_full_memory_freed{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "释放内存（MB）"
    }
   ]
  },
  {
   "title": "Minor GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_gc_minor_time_ms{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "GC耗时(毫秒)"
    },
    {
     "expr": "sum(jvm_gc_minor_count{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "GC次数"
    },
    {
     "expr": "sum(jvm_gc_minor_memory_freed{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "释放内存（MB）"
    }
   ]
  },
  {
   "title": "数据源监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "数据源 $dsJndiName",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
     "repeat": "dsJndiName",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_ds_max_size{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\",jndi=\"$dsJndiName\"})",
       "legendFormat": "最大连接数"
      },
      {
       "expr": "sum(jvm_ds_idle{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\",jndi=\"$dsJndiName\"})",
       "legendFormat": "空闲连接数"
      },
      {
       "expr": "sum(jvm_ds_used{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\",jndi=\"$dsJndiName\"})",
       "legendFormat": "活动连接数"
      },
      {
       "expr": "sum(jvm_ds_waiting{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\",jndi=\"$dsJndiName\"})",
       "legendFormat": "连接等待数"
      }
     ]
    }
   ]
  },
  { "title": "线程监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "线程汇总",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_thread_peak_total{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "线程数峰值"
    },
    {
     "expr": "sum(jvm_thread_active_total{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "活动线程数"
    },
    {
     "expr": "sum(jvm_thread_daemon_total{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "守护线程数"
    },
    {
     "expr": "sum(jvm_thread_deadlocked{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "死锁线程数"
    }
   ]
  },
  {
   "title": "线程分类",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_thread_running{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "运行态"
    },
    {
     "expr": "sum(jvm_thread_waiting{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "等待态"
    },
    {
     "expr": "sum(jvm_thread_new{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "新建态"
    },
    {
     "expr": "sum(jvm_thread_blocked{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "阻塞态"
    },
    {
     "expr": "sum(jvm_thread_terminated{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "停止态"
    }
   ]
  },
  { "title": "Class类加载、卸载监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Class类加载汇总",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 4, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_class_active_total{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "未卸载的类数目"
    },
    {
     "expr": "sum(jvm_class_unloaded_total{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\"})",
     "legendFormat": "已卸载的类数目"
    }
   ]
  },
  { "title": "Heap堆内存池监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Heap堆 $heapPoolName 内存池（单位：MB）",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 39 },
   "repeat": "heapPoolName",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_heap_mp_committed_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\",poolName=\"$heapPoolName\"})",
     "legendFormat": "已分配"
    },
    {
     "expr": "sum(jvm_heap_mp_used_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\",poolName=\"$heapPoolName\"})",
     "legendFormat": "使用中"
    }
   ]
  },
  { "title": "堆外内存池监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "堆外 $nonheapPoolName 内存池（单位：MB）",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 50 },
   "repeat": "nonheapPoolName",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_nonheap_mp_committed_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\",poolName=\"$nonheapPoolName\"})",
     "legendFormat": "已分配"
    },
    {
     "expr": "sum(jvm_nonheap_mp_used_mb{_node=~\"^$node\",_namespace=~\"^$namespace\",_container=~\"^$container\",_pod=~\"^$pod\",poolName=\"$nonheapPoolName\"})",
     "legendFormat": "使用中"
    }
   ]
  }
 ]
}